# Generated by Django 4.2 on 2026-10-06 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('issuer', models.CharField(max_length=200)),
                ('year', models.PositiveSmallIntegerField()),
                ('credential_url', models.URLField(blank=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', '-year'],
            },
        ),
        migrations.RemoveField(
            model_name='project',
            name='url',
        ),
        migrations.AddField(
            model_name='project',
            name='download_file',
            field=models.FileField(blank=True, help_text='Attach .pbix, .twbx, or .xlsx file here', upload_to='project_files/'),
        ),
        migrations.AddField(
            model_name='project',
            name='embed_url',
            field=models.TextField(blank=True, help_text='Tableau Public embed URL, Power BI iframe src, or OneDrive Excel embed link'),
        ),
        migrations.AddField(
            model_name='project',
            name='external_url',
            field=models.URLField(blank=True, help_text='Direct link to view/interact or download (Tableau Public / GitHub / Drive)'),
        ),
        migrations.AddField(
            model_name='project',
            name='key_highlights',
            field=models.TextField(blank=True, help_text='Bullet points or details separated by newlines.'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('powerbi', 'Power BI'), ('tableau', 'Tableau'), ('excel', 'Excel Model'), ('python', 'Python / Django'), ('sql', 'SQL / Data Warehouse')], default='powerbi', max_length=20),
        ),
        migrations.AlterField(
            model_name='skill',
            name='level',
            field=models.PositiveSmallIntegerField(default=85, help_text='Proficiency 0–100'),
        ),
    ]
